import { ChangeEvent, useMemo, useState } from "react";
import {
  Download,
  FileCheck2,
  FileText,
  Search,
  Upload,
  X,
} from "lucide-react";

type DocumentCategory = "Forms" | "Letters" | "Records";

type PatientDocument = {
  id: number;
  title: string;
  description: string;
  category: DocumentCategory;
  date: string;
  status: "Ready" | "Action needed";
};

const initialDocuments: PatientDocument[] = [
  {
    id: 1,
    title: "Pre-visit questionnaire",
    description: "Complete before your annual primary care visit.",
    category: "Forms",
    date: "Sep 20, 2026",
    status: "Action needed",
  },
  {
    id: 2,
    title: "Work clearance letter",
    description: "Signed by Dr. Maya Chen.",
    category: "Letters",
    date: "Aug 11, 2026",
    status: "Ready",
  },
  {
    id: 3,
    title: "Visit summary",
    description: "Primary care visit summary and instructions.",
    category: "Records",
    date: "Jul 28, 2026",
    status: "Ready",
  },
];

export default function Documents() {
  const [documents, setDocuments] = useState(initialDocuments);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<"All" | DocumentCategory>("All");
  const [selectedDocument, setSelectedDocument] =
    useState<PatientDocument | null>(null);
  const [uploadMessage, setUploadMessage] = useState("");

  const visibleDocuments = useMemo(() => {
    const search = query.trim().toLowerCase();

    return documents.filter((document) => {
      const matchesSearch =
        !search ||
        `${document.title} ${document.description}`
          .toLowerCase()
          .includes(search);

      const matchesCategory =
        category === "All" || document.category === category;

      return matchesSearch && matchesCategory;
    });
  }, [documents, query, category]);

  const downloadDocument = (document: PatientDocument) => {
    const content = [
      "CareBridge Patient Document",
      "",
      `Title: ${document.title}`,
      `Category: ${document.category}`,
      `Date: ${document.date}`,
      `Status: ${document.status}`,
      "",
      document.description,
      "",
      "Demo document generated by the CareBridge frontend.",
    ].join("\n");

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = window.document.createElement("a");

    link.href = url;
    link.download = `${document.title
      .toLowerCase()
      .replace(/\s+/g, "-")}.txt`;

    link.click();
    URL.revokeObjectURL(url);
  };

  const uploadDocument = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];

    if (!file) {
      return;
    }

    const newDocument: PatientDocument = {
      id: Date.now(),
      title: file.name,
      description: "Patient uploaded document.",
      category: "Records",
      date: new Date().toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
      }),
      status: "Ready",
    };

    setDocuments((current) => [newDocument, ...current]);
    setUploadMessage(`${file.name} uploaded successfully.`);

    event.target.value = "";
  };

  return (
    <div className="documents-page">
      <section className="documents-hero">
        <div>
          <small>DOCUMENT CENTER</small>
          <h2>Your documents</h2>
          <p>
            Find forms, letters, visit documents, and files you have uploaded.
          </p>
        </div>

        <label className="documents-upload-button">
          <Upload />
          Upload document

          <input type="file" onChange={uploadDocument} />
        </label>
      </section>

      {uploadMessage && (
        <div className="documents-upload-success">
          <FileCheck2 />
          <span>{uploadMessage}</span>

          <button onClick={() => setUploadMessage("")}>
            <X />
          </button>
        </div>
      )}

      <section className="documents-toolbar">
        <div className="documents-search">
          <Search />

          <input
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Search documents..."
          />
        </div>

        <select
          value={category}
          onChange={(event) =>
            setCategory(event.target.value as "All" | DocumentCategory)
          }
        >
          <option value="All">All documents</option>
          <option value="Forms">Forms</option>
          <option value="Letters">Letters</option>
          <option value="Records">Records</option>
        </select>
      </section>

      <section className="documents-list">
        {visibleDocuments.map((document) => (
          <article className="document-card" key={document.id}>
            <span className="document-icon">
              <FileText />
            </span>

            <div className="document-main">
              <h3>{document.title}</h3>
              <p>{document.description}</p>

              <div className="document-meta">
                <span>{document.category}</span>
                <span>{document.date}</span>
              </div>
            </div>

            <span
              className={`document-status ${
                document.status === "Ready" ? "ready" : "action"
              }`}
            >
              {document.status}
            </span>

            <div className="document-actions">
              <button onClick={() => setSelectedDocument(document)}>
                View
              </button>

              <button onClick={() => downloadDocument(document)}>
                <Download />
                Download
              </button>
            </div>
          </article>
        ))}
      </section>

      {!visibleDocuments.length && (
        <div className="documents-empty">
          No documents match your search or filter.
        </div>
      )}

      {selectedDocument && (
        <div
          className="documents-modal-backdrop"
          onClick={() => setSelectedDocument(null)}
        >
          <div
            className="documents-modal"
            onClick={(event) => event.stopPropagation()}
          >
            <button
              className="documents-modal-close"
              onClick={() => setSelectedDocument(null)}
            >
              <X />
            </button>

            <small>DOCUMENT PREVIEW</small>
            <h2>{selectedDocument.title}</h2>
            <p>{selectedDocument.description}</p>

            <div className="documents-preview">
              <FileText />

              <div>
                <span>Category</span>
                <strong>{selectedDocument.category}</strong>
              </div>

              <div>
                <span>Date</span>
                <strong>{selectedDocument.date}</strong>
              </div>

              <div>
                <span>Status</span>
                <strong>{selectedDocument.status}</strong>
              </div>
            </div>

            <button
              className="documents-primary"
              onClick={() => downloadDocument(selectedDocument)}
            >
              <Download />
              Download document
            </button>
          </div>
        </div>
      )}
    </div>
  );
}